apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/k8snetworkplumbingwg/multus-cni # {"$imagepolicy": "flux-system:multus-cni:name"}
  newTag: v4.2.0 # {"$imagepolicy": "flux-system:multus-cni:tag"}
resources:
- multus-daemonset.yaml
- repositories.yaml
