apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: ghcr.io/k8snetworkplumbingwg/multus-cni # {"$imagepolicy": "flux-system:multus-cni:name"}
  newTag: v4.2.2 # {"$imagepolicy": "flux-system:multus-cni:tag"}
resources:
- multus-daemonset.yaml
- repositories.yaml
patches:
- target:
    kind: DaemonSet
    name: kube-multus-ds
    namespace: kube-system
  path: cni-plugins.yaml
