---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 99-default
  namespace: flux-system
spec:
  dependsOn:
  - name: 03-stage
  interval: 15m
  path: ./configs/clusters/production/99-default
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  components:
  - ../../components/images
  healthChecks:
  - apiVersion: v1
    kind: Secret
    name: d20-fan-tls
    namespace: cert-manager
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 99-default
  namespace: flux-system
spec:
  dependsOn:
  - name: 03-stage
  interval: 15m
  path: ./configs/clusters/production/99-continuous
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  components:
  - ../../components/images
