#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: 04-stage
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: 03-stage
#  interval: 1m0s
#  path: ./configs/clusters/production/04-stage
#  prune: true
#  sourceRef:
#    kind: GitRepository
#    name: configs
#  healthChecks:
#    - apiVersion: v1
#      kind: Secret
#      name: vault-kms-key
#      namespace: vault
#    - apiVersion: v1
#      kind: ConfigMap
#      name: vault-helm-chart-value-overrides
#      namespace: vault
