---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1h0s
  url: https://helm.releases.hashicorp.com
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 1m0s
  chart:
    spec:
      chart: vault
      sourceRef:
        kind: HelmRepository
        name: vault
  valuesFrom:
  - kind: ConfigMap
    name: "vault-helm-chart-value-overrides"
    valuesKey: values.yaml
