---
kind: Namespace
apiVersion: v1
metadata:
  name: vault-secrets-operator
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: vault-secrets-operator
  namespace: vault-secrets-operator
spec:
  interval: 1m0s
  chart:
    spec:
      chart: vault-secrets-operator
      version: ">=0.0.0-0" # TODO(fancl): remove after stable release
      sourceRef:
        kind: HelmRepository
        name: vault
        namespace: vault
  values:
    defaultVaultConnection:
      enabled: true
      address: http://vault.vault.svc:8200/
      skipTLSVerify: true # TODO(fancl): FIXME
