---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fetch-latest
  namespace: continuous
spec:
  params:
    - name: FETCHER_IMAGE
      description: Tag of the fetcher image.
  workspaces:
    - name: scripts
      mountPath: /scripts
  results:
    - name: VERSION
      description: Version of the image to be built.
    - name: URL
      description: URL of the release to be downloaded.
  steps:
    - name: fetch-version
      image: $(params.FETCHER_IMAGE)
      script: bash /scripts/fetch-latest.sh
      env:
      - name: RESULT_VERSION
        value: $(results.VERSION.path)
      - name: RESULT_URL
        value: $(results.URL.path)
