---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: fetch-latest
  namespace: continuous
spec:
  params:
    - name: FETCHER_TAG
      description: Tag of the fetcher image.
    - name: SCRIPT
      description: Script updates the results.
  results:
    - name: VERSION
      description: Version of the image to be built.
    - name: URL
      description: URL of the release to be downloaded.
  steps:
    - name: fetch-version
      image: registry.local.d20.fan/fancl20/fetcher:$(params.FETCHER_TAG)
      script: $(params.SCRIPT)
