apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: kaniko
  namespace: continuous
spec:
  params:
    - name: IMAGE
      description: Name (reference) of the image to build.
    - name: DOCKERFILE
      description: Path to the Dockerfile to build.
      default: ./Dockerfile
    - name: CONTEXT
      description: The build context used by Kaniko.
      default: ./
    - name: CONTEXT_SUB_PATH
      description: Sub path within the given context
      default: ./
    - name: EXTRA_ARGS
      type: array
      default: []
  workspaces:
    - name: dockerconfig
      description: Includes a docker `config.json`
      optional: true
      mountPath: /kaniko/.docker
  results:
    - name: IMAGE_DIGEST
      description: Digest of the image just built.
    - name: IMAGE_URL
      description: URL of the image just built.
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.20.1 # {"$imagepolicy": "flux-system:kaniko"}
      args:
        - $(params.EXTRA_ARGS)
        - --dockerfile=$(params.DOCKERFILE)
        - --context=$(params.CONTEXT)
        - --context-sub-path=$(params.CONTEXT_SUB_PATH)
        - --destination=$(params.IMAGE)
        - --digest-file=$(results.IMAGE_DIGEST.path)
      # kaniko assumes it is running as root, which means this example fails on platforms
      # that default to run containers as random uid (like OpenShift). Adding this securityContext
      # makes it explicit that it needs to run as root.
      securityContext:
        runAsUser: 0
    - name: write-url
      image: docker.io/library/bash:5.2.26 # {"$imagepolicy": "flux-system:bash"}
      script: |
        set -e
        image="$(params.IMAGE)"
        echo -n "${image}" | tee "$(results.IMAGE_URL.path)"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: kaniko
  namespace: flux-system
spec:
  image: gcr.io/kaniko-project/executor
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: kaniko
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: kaniko
  policy:
    semver:
      range: "*"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: bash
  namespace: flux-system
spec:
  image: docker.io/library/bash
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: bash
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: bash
  policy:
    semver:
      range: "*"
