apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: skopeo
  namespace: continuous
spec:
  params:
    - name: ARGS
      type: array
      default: []
  results:
    - name: EXIT_CODE
  steps:
    - name: skopeo
      image: quay.io/skopeo/stable:v1.13.3 # {"$imagepolicy": "flux-system:skopeo"}
      args:
        - $(params.ARGS)
      onError: continue
    - name: write-output
      image: docker.io/library/bash:5.2.37 # {"$imagepolicy": "flux-system:bash"}
      script: |
        set -e
        cat "$(steps.skopeo.exitCode.path)" | tee "$(results.EXIT_CODE.path)"
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: skopeo
  namespace: flux-system
spec:
  image: quay.io/skopeo/stable
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: skopeo
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: skopeo
  policy:
    semver:
      range: "*"