{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": null,
      "name": "qbittorrent-p2p",
      "namespace": "default"
   },
   "spec": {
      "name": "qbittorrent-p2p",
      "ports": [
         {
            "name": "tcp",
            "port": 6881,
            "protocol": "TCP",
            "targetPort": 6881
         },
         {
            "name": "udp",
            "port": 6881,
            "protocol": "UDP",
            "targetPort": 6881
         }
      ],
      "selector": {
         "app.kubernetes.io/name": "qbittorrent"
      },
      "type": "ClusterIP"
   }
}
