---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dae-scripts
  namespace: continuous
data:
  fetch-latest.sh: |
    set -ex
    curl -s --fail -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/daeuniverse/daed/releases/latest > metadata.json
    cat metadata.json | jq -rj '.tag_name' > "${RESULT_VERSION}"
    cat metadata.json | jq -rj '.assets[] | select(.name=="daed-linux-x86_64_v2_sse.zip") | .browser_download_url' > "${RESULT_URL}"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: dae
  namespace: continuous
spec:
  params:
  - name: image
    value: dae
