---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fava-scripts
  namespace: continuous
data:
  fetch-latest.sh: |
    set -ex
    curl -s --fail -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/beancount/fava/tags > metadata.json
    FAVA_VERSION=$(cat metadata.json | jq -rj '.[0].name')
    echo -n "${FAVA_VERSION}" > "${RESULT_VERSION}"
    echo "fava==${FAVA_VERSION#v}" > "${RESULT_URL}"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: fava
  namespace: continuous
spec:
  params:
  - name: image
    value: fava
