apiVersion: v1
kind: ConfigMap
metadata:
  name: fetcher-scripts
  namespace: continuous
data:
  fetch-latest.sh: |
    set -ex
    echo -n "v0.3.0" > "${RESULT_VERSION}"
    echo -n "" > "${RESULT_URL}"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: fetcher
  namespace: continuous
spec:
  params:
  - name: image
    value: fetcher
  - name: fetcher_image
    value: docker.io/library/bash:5.2.37 # {"$imagepolicy": "flux-system:bash"}
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: fetcher
  namespace: flux-system
spec:
  image: registry.local.d20.fan/fancl20/fetcher
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: fetcher
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: fetcher
  policy:
    semver:
      range: '*-testing-'
