---
apiVersion: v1
kind: ConfigMap
metadata:
  name: workspace-scripts
  namespace: continuous
data:
  fetch-latest.sh: |
    set -ex
    echo -n "$(date  +"%Y%U")" > "${RESULT_VERSION}"
    echo > "${RESULT_URL}"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: workspace
  namespace: continuous
spec:
  params:
  - name: image
    value: workspace
