{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "unifi",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "unifi"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": {
               "vault.hashicorp.com/agent-init-first": "true",
               "vault.hashicorp.com/agent-inject": "true",
               "vault.hashicorp.com/agent-inject-secret-unifi_mongo_pass": "homeserver/data/unifi",
               "vault.hashicorp.com/agent-inject-template-unifi_mongo_pass": "{{ with secret \"homeserver/data/unifi\" -}}{{ .Data.data.db_password }}{{- end }}",
               "vault.hashicorp.com/agent-pre-populate-only": "true",
               "vault.hashicorp.com/role": "unifi"
            },
            "labels": {
               "app.kubernetes.io/name": "unifi"
            }
         },
         "spec": {
            "containers": [
               {
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     },
                     {
                        "name": "MONGO_HOST",
                        "value": "127.0.0.1"
                     },
                     {
                        "name": "MONGO_PORT",
                        "value": "27017"
                     },
                     {
                        "name": "MONGO_DBNAME",
                        "value": "unifi"
                     },
                     {
                        "name": "MONGO_USER",
                        "value": "unifi"
                     },
                     {
                        "name": "FILE__MONGO_PASS",
                        "value": "/vault/secrets/unifi_mongo_pass"
                     }
                  ],
                  "image": "lscr.io/linuxserver/unifi-network-application",
                  "name": "unifi",
                  "volumeMounts": [
                     {
                        "mountPath": "/config",
                        "name": "data",
                        "subPath": "unifi/data/config"
                     }
                  ]
               },
               {
                  "command": [
                     "mongod",
                     "--bind_ip",
                     "127.0.0.1"
                  ],
                  "image": "docker.io/library/mongo",
                  "name": "mongo",
                  "volumeMounts": [
                     {
                        "mountPath": "/data/db",
                        "name": "data",
                        "subPath": "unifi/data/db"
                     },
                     {
                        "mountPath": "/docker-entrypoint-initdb.d",
                        "name": "config"
                     }
                  ]
               }
            ],
            "serviceAccountName": "unifi",
            "volumes": [
               {
                  "name": "data",
                  "persistentVolumeClaim": {
                     "claimName": "mass-storage"
                  }
               },
               {
                  "configMap": {
                     "name": "unifi"
                  },
                  "name": "config"
               }
            ]
         }
      }
   }
}
