{
   "apiVersion": "kustomize.config.k8s.io/v1beta1",
   "configMapGenerator": [
      {
         "files": [
            "10-init-mongo.sh"
         ],
         "name": "unifi",
         "namespace": "default"
      }
   ],
   "kind": "Kustomization",
   "resources": [
      "deployment.yaml",
      "serviceaccount.yaml"
   ]
}
