{
   "apiVersion": "source.toolkit.fluxcd.io/v1",
   "kind": "HelmRepository",
   "metadata": {
      "name": "coder",
      "namespace": "coder"
   },
   "spec": {
      "interval": "1h0s",
      "url": "https://helm.coder.com/v2"
   }
}
