{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": { },
      "name": "coder-db",
      "namespace": "coder"
   },
   "spec": {
      "ports": [
         {
            "name": "postgres",
            "port": 5432,
            "protocol": "TCP",
            "targetPort": 5432
         }
      ],
      "selector": {
         "app.kubernetes.io/name": "coder-db"
      },
      "type": "ClusterIP"
   }
}
