---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: configs
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/fancl20/homeserver-configs.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 00-stage
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./configs/clusters/production/00-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
