{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ default (include "service-chart.name" $) .name }}
  labels:
    {{- include "service-chart.labels" $ | nindent 4 }}
  annotations:
    {{- if .externalDNS }}
    external-dns.alpha.kubernetes.io/hostname: {{ include "service-chart.hostname" $ }}
    {{- end}}
    
spec:
  {{- $type := (default "ClusterIP" .type) }}
  type: {{ $type }}
  {{- if eq $type "LoadBalancer" }}
  allocateLoadBalancerNodePorts: false
  {{- end}}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- if or .ports .portsRanges }}
  ports:
  {{- end }}
  {{- with .ports }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- range .portsRanges }}
  {{- $portsRange := . -}}
  {{- range untilStep ( .start | int ) ( .end | int ) 1 }}
    - name: "{{ $portsRange.prefix }}-{{ . }}"
      protocol: "{{ $portsRange.protocol }}"
      port: {{ . }}
      targetPort: {{ . }}
  {{- end }}
  {{- end }}
  selector:
    {{- include "service-chart.selectorLabels" $ | nindent 4 }}
---
{{- end }}