---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 02-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 01-stage
  interval: 1m0s
  path: ./configs/clusters/production/02-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: vault-kms-key
      namespace: vault
    - apiVersion: v1
      kind: ConfigMap
      name: vault-helm-chart-value-overrides
      namespace: vault
