# tf-controller-key is managed by 01-stage and required by 01-stage.
# For bootstrapping, the terraform need to be manually applied.
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: 01-stage
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./configs/clusters/production/01-stage
  backendConfig:
    disable: true
  approvePlan: auto
  disableDriftDetection: false # avoid constantly accessing gcp
  sourceRef:
    kind: GitRepository
    name: configs
  runnerPodTemplate:
    spec:
      envFrom:
        - secretRef:
            name: tf-controller-key
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 02-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 01-stage
  interval: 1m0s
  path: ./configs/clusters/production/02-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: vault-kms-key
      namespace: vault
