# tf-controller-key is managed by 01-stage and required by 01-stage.
# For bootstrapping, the terraform need to be manually applied.
---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: 01-stage
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./configs/clusters/production/01-stage
  backendConfig:
    customConfiguration: |
      backend "gcs" {
        bucket = "0c9cfd1d-dc77-43e6-9131-d5535a91d844"
        prefix = "terraform/state/clusters/production/01-stage"
      }
  approvePlan: auto
  disableDriftDetection: false # avoid constantly accessing gcp
  sourceRef:
    kind: GitRepository
    name: configs
  varsFrom:
    - kind: Secret
      name: tf-controller-key
