{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": null,
      "name": {
         "name": "qbittorrent-p2p",
         "ports": [
            {
               "name": "tcp",
               "port": 6881,
               "protocol": "TCP",
               "targetPort": 6881
            },
            {
               "name": "udp",
               "port": 6881,
               "protocol": "udp",
               "targetPort": 6881
            }
         ]
      },
      "namespace": "default"
   },
   "spec": {
      "name": "qbittorrent-ui",
      "ports": [
         {
            "name": "webui",
            "port": 80,
            "protocol": "TCP",
            "targetPort": 8080
         }
      ],
      "selector": {
         "app.kubernetes.io/name": "qbittorrent"
      },
      "type": "ClusterIP"
   }
}
