---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  name: source-controller
  namespace: flux-system
spec:
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: admin
    serviceAccount: source-controller
---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: configs
  namespace: flux-system
spec:
  vaultAuthRef: source-controller
  mount: homeserver
  type: kv-v2
  path: github_pat
  refreshAfter: 60s
  destination:
    name: configs