---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: source-controller
  namespace: flux-system
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200/
      path: homeserver
      auth:
        kubernetes:
          mountPath: kubernetes
          role: source-controller
          serviceAccountRef:
            name: source-controller
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: configs
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: source-controller
    kind: SecretStore
  target:
    name: configs
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: github_pat
---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: configs
  namespace: flux-system
spec:
  interval: 30m
  sourceRef:
    kind: GitRepository
    name: configs
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  update:
    path: ./configs/clusters
    strategy: Setters