---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: notification-controller
  namespace: flux-system
spec:
  provider:
    vault:
      server: http://vault.vault.svc:8200/
      path: homeserver
      auth:
        kubernetes:
          mountPath: kubernetes
          role: notifier
          serviceAccountRef:
            name: notification-controller
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: slack-token
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: notification-controller
    kind: SecretStore
  target:
    name: slack-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: slack
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: slack
  namespace: flux-system
spec:
  type: slack
  channel: notifications
  address: https://slack.com/api/chat.postMessage
  secretRef:
    name: slack-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: slack
  namespace: flux-system
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: Terraform
    name: '*'
  exclusionList:
  - "^Dependencies.*" # https://github.com/fluxcd/kustomize-controller/issues/492
