---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: tf-gcp-token
  namespace: flux-system
spec:
  path: "/gcp/roleset/admin/token"
  method: "GET"
  provider:
    server: http://vault.vault.svc:8200/
    auth:
      kubernetes:
        mountPath: kubernetes
        role: admin
        serviceAccountRef:
          name: tf-runner
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: tf-vault-token
  namespace: flux-system
spec:
  path: "/auth/token/lookup-self"
  method: "GET"
  provider:
    server: http://vault.vault.svc:8200/
    auth:
      kubernetes:
        mountPath: kubernetes
        role: admin
        serviceAccountRef:
          name: tf-runner
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tf-runner
  namespace: flux-system
spec:
  refreshInterval: 8h
  target:
    name: clouddns-dns01-solver-svc-acct
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        VAULT_TOKEN: "{{ $var := .vault | fromJson }}{{ $var.id }}"
        GOOGLE_OAUTH_ACCESS_TOKEN: "{{ $var := .gcp | fromJson }}{{ $var.token }}"
  data:
  - secretKey: gcp
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: tf-gcp-token
  - secretKey: vault
    sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: tf-vault-token