apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: lscr.io/linuxserver/beets # {"$imagepolicy": "default:beets:name"}
  newTag: 1.6.0-ls179 # {"$imagepolicy": "default:beets:tag"}