---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 99-services
  namespace: flux-system
spec:
  dependsOn:
  - name: 05-stage
  interval: 15m
  path: ./configs/clusters-ng/production/99-services
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  components:
  - ../../components/terraform
  postBuild:
    substitute:
      layer_name: 99-services

