# Used in components/terrafrom
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: tf-runner
  namespace: flux-system
spec:
  image: ghcr.io/flux-iac/tf-runner
  interval: 1h
  exclusionList:
    - '^.*\.sig$'
    - '^.*-base$'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: tf-runner
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: tf-runner
  policy:
    semver:
      range: '*-rc'
