---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: temporal
  namespace: default
spec:
  interval: 1h0s
  url: https://go.temporal.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: temporal
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: temporal
      sourceRef:
        kind: HelmRepository
        name: temporal
  values:
    server:
      replicaCount: 1
    cassandra:
      config:
        cluster_size: 1
    elasticsearch:
      replicas: 1
    prometheus:
      enabled: false
    grafana:
      enabled: false
