---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: clouddns
  namespace: cert-manager
spec:
  path: "/gcp/roleset/certbot/key"
  method: "GET"
  provider:
    server: http://vault.vault.svc:8200/
    auth:
      kubernetes:
        mountPath: kubernetes
        role: certbot
        serviceAccountRef:
          name: cert-manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clouddns
  namespace: cert-manager
spec:
  refreshInterval: 20h
  target:
    name: clouddns-dns01-solver-svc-acct
    creationPolicy: Owner
    engineVersion: v2
    data:
      private_key_data: "{{ .private_key_data | b64dec }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: clouddns