{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "bind9",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "bind9"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "bind9"
            }
         },
         "spec": {
            "containers": [
               {
                  "image": "internetsystemsconsortium/bind9",
                  "name": "bind9",
                  "resources": {
                     "limits": {
                        "cpu": "200m",
                        "memory": "128Mi"
                     },
                     "requests": {
                        "cpu": "100m",
                        "memory": "128Mi"
                     }
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/etc/bind/named.conf",
                        "name": "config",
                        "subPath": "named.conf"
                     },
                     {
                        "mountPath": "/var/lib/bind/local.d20.fan.zone",
                        "name": "config",
                        "subPath": "local.d20.fan.zone"
                     },
                     {
                        "mountPath": "/etc/bind/bind9_externaldns_key",
                        "name": "secret",
                        "subPath": "bind9_externaldns_key"
                     }
                  ]
               }
            ],
            "serviceAccountName": "bind9",
            "volumes": [
               {
                  "configMap": {
                     "name": "bind9"
                  },
                  "name": "config"
               },
               {
                  "name": "secret",
                  "secret": {
                     "secretName": "bind9"
                  }
               }
            ]
         }
      }
   }
}
