{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "annotations": {
         "kustomize.toolkit.fluxcd.io/substitute": "disabled"
      },
      "name": "chrome-devtools-mcp",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "chrome-devtools-mcp"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "chrome-devtools-mcp"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "npx",
                     "-y",
                     "supergateway",
                     "--stdio",
                     "npx -y chrome-devtools-mcp@latest \\\n  --executablePath=/opt/chrome/chrome \\\n  --slim \\\n  --headless \\\n  --isolated\n",
                     "--outputTransport",
                     "streamableHttp",
                     "--stateful",
                     "--cors"
                  ],
                  "env": [
                     {
                        "name": "HOME",
                        "value": "/tmp"
                     }
                  ],
                  "image": "registry.local.d20.fan/fancl20/chrome",
                  "name": "chrome-devtools-mcp",
                  "securityContext": {
                     "appArmorProfile": {
                        "type": "Unconfined"
                     },
                     "seccompProfile": {
                        "type": "Unconfined"
                     }
                  }
               }
            ],
            "enableServiceLinks": false,
            "securityContext": {
               "fsGroup": 1000,
               "fsGroupChangePolicy": "OnRootMismatch",
               "runAsGroup": 1000,
               "runAsUser": 1000
            },
            "serviceAccountName": "chrome-devtools-mcp",
            "volumes": [ ]
         }
      }
   }
}
