deployment:
  replicaCount: 1
  podAnnotations: {}
  image:
    repository: ""
    pullPolicy: IfNotPresent
    tag: ""
  securityContext: {}
  command: []
  args: []
  env: []
  resources: {}
  volumeMounts: []
  volumes: []
  nodeSelector: {}
  tolerations: []
  affinity: {}

serviceAccount:
  create: true
  annotations: {}
  name: ""

services: []

ingress:
  enabled: false
  annotations: {}
  hostname: ""
  backend:
    service: ""
    port: 80

domainSuffix: ""