{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "bind9",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "bind9"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": {
               "vault.hashicorp.com/agent-init-first": "true",
               "vault.hashicorp.com/agent-inject": "true",
               "vault.hashicorp.com/agent-inject-secret-bind9_externaldns_key": "homeserver/data/bind9",
               "vault.hashicorp.com/agent-inject-template-bind9_externaldns_key": "{{ with secret \"homeserver/data/bind9\" -}}\nkey externaldns-key {\n  algorithm {{ .Data.data.externaldns_key_algorithm }};\n  secret \"{{ .Data.data.externaldns_key_secret }}\";\n};\n{{- end }}\n",
               "vault.hashicorp.com/agent-pre-populate-only": "true",
               "vault.hashicorp.com/role": "external_dns"
            },
            "labels": {
               "app.kubernetes.io/name": "bind9"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/bin/sh",
                     "-e",
                     "-c",
                     "rm -f /etc/bind/pri/*.jnl\nexec /usr/sbin/named -g -c /etc/bind/named.conf -u bind\n"
                  ],
                  "image": "internetsystemsconsortium/bind9",
                  "name": "bind9",
                  "resources": {
                     "limits": {
                        "cpu": "200m",
                        "memory": "128Mi"
                     },
                     "requests": {
                        "cpu": "100m",
                        "memory": "128Mi"
                     }
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/etc/bind/named.conf",
                        "name": "config",
                        "subPath": "named.conf"
                     },
                     {
                        "mountPath": "/etc/bind/local.d20.fan.zone",
                        "name": "config",
                        "subPath": "local.d20.fan.zone"
                     }
                  ]
               }
            ],
            "serviceAccountName": "bind9",
            "volumes": [
               {
                  "configMap": {
                     "name": "bind9"
                  },
                  "name": "config"
               }
            ]
         }
      }
   }
}
