{
   "apiVersion": "kustomize.config.k8s.io/v1beta1",
   "configMapGenerator": [
      {
         "files": [
            "local.d20.fan.zone",
            "named.conf"
         ],
         "name": "bind9"
      }
   ],
   "kind": "Kustomization",
   "resources": [
      "deployment.yaml",
      "service_bind9.yaml",
      "serviceaccount.yaml"
   ]
}
