---
apiVersion: generators.external-secrets.io/v1alpha1
kind: VaultDynamicSecret
metadata:
  name: clouddns
  namespace: cert-manager
spec:
  path: "/gcp/roleset/cert-manager/key"
  method: "POST"
  parameters:
    ttl: 24h
  provider:
    server: http://vault.vault.svc:8200/
    auth:
      kubernetes:
        mountPath: kubernetes
        role: cert_manager
        serviceAccountRef:
          name: cert-manager
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: clouddns
  namespace: cert-manager
spec:
  refreshInterval: 20h
  target:
    name: clouddns-dns01-solver-svc-acct
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        service-account.json: "{{ .private_key_data | b64dec }}"
  dataFrom:
  - sourceRef:
      generatorRef:
        apiVersion: generators.external-secrets.io/v1alpha1
        kind: VaultDynamicSecret
        name: clouddns
