---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: clouddns
  namespace: cert-manager
spec:
  acme:
    email: fancl20@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: clouddns-issuer-account-key
    solvers:
    - dns01:
        cloudDNS:
          project: home-servers-275405
          serviceAccountSecretRef:
            name: clouddns-dns01-solver-svc-acct
            key: service-account.json
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: d20-fan
  namespace: cert-manager
spec:
  secretName: d20-fan-tls
  issuerRef:
    name: clouddns
  dnsNames:
  - '*.local.d20.fan'
