{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImageRepository",
   "metadata": {
      "name": "beets",
      "namespace": "flux-system"
   },
   "spec": {
      "image": "lscr.io/linuxserver/beets",
      "interval": "1h"
   }
}
