{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImageRepository",
   "metadata": {
      "name": "external-dns",
      "namespace": "flux-system"
   },
   "spec": {
      "image": "registry.k8s.io/external-dns/external-dns",
      "interval": "1h"
   }
}
