{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImageRepository",
   "metadata": {
      "name": "fava",
      "namespace": "flux-system"
   },
   "spec": {
      "image": "registry.local.d20.fan/fancl20/fava",
      "interval": "1h"
   }
}
