{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "qbittorrent",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "pattern": ".*-ls\\d{3,}"
      },
      "imageRepositoryRef": {
         "name": "qbittorrent"
      },
      "policy": {
         "semver": {
            "range": "*-r0-ls"
         }
      }
   }
}
