{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "unifi",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "pattern": ".*-ls"
      },
      "imageRepositoryRef": {
         "name": "unifi"
      },
      "policy": {
         "semver": {
            "range": "*-ls"
         }
      }
   }
}
