{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "registry",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "registry"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "registry"
            }
         },
         "spec": {
            "containers": [
               {
                  "image": "docker.io/library/registry",
                  "name": "registry",
                  "volumeMounts": [
                     {
                        "mountPath": "/var/lib/registry",
                        "name": "registry"
                     }
                  ]
               }
            ],
            "serviceAccountName": "registry",
            "volumes": [
               {
                  "name": "registry",
                  "persistentVolumeClaim": {
                     "claimName": "registry"
                  }
               }
            ]
         }
      }
   }
}
