apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- workflows.yaml
- namespace.yaml
- ingress.yaml
patches:
- patch: |
    - op: add
      path: /spec/template/spec/containers/0/args/1
      value: --auth-mode=server
    - op: add
      path: /spec/template/spec/containers/0/args/2
      value: --access-control-allow-origin=*
  target:
    kind: Deployment
    name: argo-server
    namespace: argo
