{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "fava",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "fava"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "fava"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/usr/local/bin/fava",
                     "--port",
                     "5000",
                     "/workspace/main.beancount"
                  ],
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     }
                  ],
                  "image": "registry.local.d20.fan/fancl20/fava",
                  "name": "fava",
                  "volumeMounts": [
                     {
                        "mountPath": "/workspace",
                        "name": "fava"
                     }
                  ]
               }
            ],
            "serviceAccountName": "fava",
            "volumes": [
               {
                  "name": "fava",
                  "persistentVolumeClaim": {
                     "claimName": "fava"
                  }
               }
            ]
         }
      }
   }
}
