"dns":
  "enable": true
  "enhanced-mode": "fake-ip"
  "fake-ip-filter":
  - "time.windows.com"
  - "+.playstation.*"
  - "+.local.d20.fan"
  "fake-ip-range": "198.18.0.0/16"
  "listen": "0.0.0.0:53"
  "nameserver":
  - "udp://192.168.1.1:53"
"ebpf":
  "redirect-to-tun":
  - "net1"
"external-controller": "0.0.0.0:9090"
"external-ui": "clash-dashboard-gh-pages"
"interface-name": "net1"
"ipv6": false
"mode": "Rule"
"routing-mark": 1
"rules":
- "SCRIPT,genshin,SG1-SG2-CN2"
- "SCRIPT,mihoyo,JP2"
- "GEOIP,CN,JP2"
- "MATCH,DIRECT"
"script":
  "engine": "expr"
  "shortcuts":
    "genshin": "network == \"udp\" and dst_port in [22101, 22102]"
    "mihoyo": "host in [\"log-upload.mihoyo.com\", \"sdk-static.mihoyo.com\", \"hk4e-sdk.mihoyo.com\"]"
"tun":
  "enable": true
  "stack": "system"