---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 00-stage
  interval: 15m
  path: ./configs/clusters-ng/production/01-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  components:
  - ../../components/terraform
  postBuild:
    substitute:
      layer_name: 01-stage
  healthChecks:
  # tofu-controller
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: terraforms.infra.contrib.fluxcd.io
  # metallb
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ipaddresspools.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: l2advertisements.metallb.io
  # ingress-nginx
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: ingress-nginx
    namespace: ingress-nginx
  # onepassword-operator
  #- apiVersion: apiextensions.k8s.io/v1
  #  kind: CustomResourceDefinition
  #  name: onepassworditems.onepassword.com
