{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "sftp",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "sftp"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "sftp"
            }
         },
         "spec": {
            "containers": [
               {
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     },
                     {
                        "name": "PUID",
                        "value": "1000"
                     },
                     {
                        "name": "GUID",
                        "value": "1000"
                     },
                     {
                        "name": "PASSWORD_ACCESS",
                        "value": "true"
                     },
                     {
                        "name": "USER_NAME",
                        "value": "fancl20"
                     }
                  ],
                  "envFrom": [
                     {
                        "secretRef": {
                           "name": "sftp"
                        }
                     }
                  ],
                  "image": "lscr.io/linuxserver/openssh-server",
                  "name": "sftp",
                  "volumeMounts": [
                     {
                        "mountPath": "/config",
                        "name": "sftp"
                     },
                     {
                        "mountPath": "/shared",
                        "name": "data"
                     }
                  ]
               }
            ],
            "serviceAccountName": "sftp",
            "volumes": [
               {
                  "name": "data",
                  "persistentVolumeClaim": {
                     "claimName": "shared-data"
                  }
               },
               {
                  "name": "sftp",
                  "persistentVolumeClaim": {
                     "claimName": "sftp"
                  }
               }
            ]
         }
      }
   }
}
