{
   "apiVersion": "external-secrets.io/v1",
   "kind": "ExternalSecret",
   "metadata": {
      "name": "sftp",
      "namespace": "default"
   },
   "spec": {
      "dataFrom": [
         {
            "extract": {
               "key": "Shared SFTP",
               "property": "public key"
            },
            "rewrite": [
               {
                  "regexp": {
                     "source": "public key",
                     "target": "PUBLIC_KEY"
                  }
               }
            ]
         },
         {
            "extract": {
               "key": "Shared SFTP",
               "property": "password"
            },
            "rewrite": [
               {
                  "regexp": {
                     "source": "password",
                     "target": "USER_PASSWORD"
                  }
               }
            ]
         }
      ],
      "refreshInterval": "1m",
      "secretStoreRef": {
         "kind": "ClusterSecretStore",
         "name": "onepassword"
      },
      "target": {
         "creationPolicy": "Owner",
         "name": "sftp"
      }
   }
}
