{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "dae",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "dae"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": {
               "k8s.v1.cni.cncf.io/networks": "[\n    {\n        \"gateway\": [\n            \"192.168.1.1\"\n        ],\n        \"ips\": [\n            \"192.168.1.245/24\"\n        ],\n        \"mac\": \"26:1e:94:c2:23:40\",\n        \"name\": \"macvlan\"\n    }\n]",
               "vault.hashicorp.com/agent-init-first": "true",
               "vault.hashicorp.com/agent-inject": "true",
               "vault.hashicorp.com/agent-inject-secret-node.dae": "homeserver/data/dae",
               "vault.hashicorp.com/agent-inject-template-node.dae": "{{ with secret \"homeserver/data/dae\" -}}\n{{ index .Data.data.config }}\n{{- end }}\n",
               "vault.hashicorp.com/agent-pre-populate-only": "true",
               "vault.hashicorp.com/role": "proxy"
            },
            "labels": {
               "app.kubernetes.io/name": "dae"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/bin/bash",
                     "-ex",
                     "-c",
                     "mkdir -p /etc/dae\ncat /config/config.dae <(echo) /vault/secrets/node.dae > /etc/dae/config.dae\nchmod 0600 /etc/dae/config.dae\n\nmount bpffs /sys/fs/bpf/ -t bpf\n\nip route replace 10.96.0.0/12 via 10.244.0.1 # serviceCIDR\nip route replace default via 192.168.1.1 dev net1\n\nexec /opt/dae/dae-linux-x86_64 run --disable-timestamp -c /etc/dae/config.dae\n"
                  ],
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     }
                  ],
                  "image": "registry.local.d20.fan/fancl20/dae",
                  "name": "dae",
                  "securityContext": {
                     "capabilities": {
                        "add": [
                           "NET_ADMIN",
                           "SYS_MODULE",
                           "SYS_ADMIN"
                        ]
                     }
                  },
                  "volumeMounts": [
                     {
                        "mountPath": "/config",
                        "name": "config"
                     }
                  ]
               }
            ],
            "securityContext": {
               "sysctls": [
                  {
                     "name": "net.ipv4.conf.net1.forwarding",
                     "value": "1"
                  },
                  {
                     "name": "net.ipv6.conf.net1.forwarding",
                     "value": "1"
                  },
                  {
                     "name": "net.ipv4.conf.net1.send_redirects",
                     "value": "0"
                  },
                  {
                     "name": "net.ipv4.ip_forward",
                     "value": "1"
                  }
               ]
            },
            "serviceAccountName": "dae",
            "volumes": [
               {
                  "configMap": {
                     "name": "dae"
                  },
                  "name": "config"
               }
            ]
         }
      }
   }
}
