{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": null,
      "name": "bind9",
      "namespace": "default"
   },
   "spec": {
      "allocateLoadBalancerNodePorts": false,
      "ports": [
         {
            "name": "dns-udp",
            "port": 53,
            "protocol": "UDP",
            "targetPort": 5353
         },
         {
            "name": "dns-tcp",
            "port": 53,
            "protocol": "TCP",
            "targetPort": 5353
         }
      ],
      "selector": {
         "app.kubernetes.io/name": "bind9"
      },
      "type": "LoadBalancer"
   }
}
