---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: telegram-token
  namespace: flux-system
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: telegram-token
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: Telegram Bot Token
      property: credential
    rewrite:
    - regexp:
        source: credential
        target: token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: telegram
  namespace: flux-system
spec:
  type: telegram
  address: https://api.telegram.org
  channel: '@fancl20_cluster'
  secretRef:
    name: telegram-token
---
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: telegram
  namespace: flux-system
spec:
  providerRef:
    name: telegram
  eventSeverity: info
  eventSources:
  - kind: GitRepository
    name: '*'
  - kind: Kustomization
    name: '*'
  - kind: HelmRelease
    name: '*'
  - kind: Terraform
    name: '*'
  exclusionList:
  - "^Dependencies.*" # https://github.com/fluxcd/kustomize-controller/issues/492
