# For bootstrapping, the terraform need to be manually applied.
bases:
- ../../../base/terraform
patches:
- target:
    kind: Terraform
  patch: |-
    - op: replace
      path: /metadata/name
      value: 03-stage
    - op: replace
      path: /spec/path
      value: ./configs/clusters/production/03-stage
