{
   "apiVersion": "external-secrets.io/v1",
   "kind": "ExternalSecret",
   "metadata": {
      "name": "external-dns",
      "namespace": "default"
   },
   "spec": {
      "dataFrom": [
         {
            "extract": {
               "key": "bind9"
            },
            "rewrite": [
               {
                  "regexp": {
                     "source": "externaldns_key_secret",
                     "target": "EXTERNAL_DNS_RFC2136_TSIG_SECRET"
                  }
               },
               {
                  "regexp": {
                     "source": "externaldns_key_algorithm",
                     "target": "EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG"
                  }
               }
            ]
         }
      ],
      "refreshInterval": "1m",
      "secretStoreRef": {
         "kind": "SecretStore",
         "name": "external-dns"
      },
      "target": {
         "creationPolicy": "Owner",
         "name": "external-dns"
      }
   }
}
