{
   "apiVersion": "external-secrets.io/v1beta1",
   "kind": "SecretStore",
   "metadata": {
      "name": "external-dns",
      "namespace": "default"
   },
   "spec": {
      "provider": {
         "vault": {
            "auth": {
               "kubernetes": {
                  "mountPath": "kubernetes",
                  "role": "external_dns",
                  "serviceAccountRef": {
                     "name": "external-dns"
                  }
               }
            },
            "path": "homeserver",
            "server": "http://vault.vault.svc:8200/"
         }
      }
   }
}
