apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.1.2
    port: 6443
    k0sApiPort: 9443
    sans:
    - 192.168.1.2
  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.1.2
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: kuberouter
    kubeProxy:
      mode: nftables
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  telemetry:
    enabled: true
  installConfig:
    users:
      etcdUser: k0s-etcd
      kineUser: k0s-kube-apiserver
      konnectivityUser: k0s-konnectivity-server
      kubeAPIserverUser: k0s-kube-apiserver
      kubeSchedulerUser: k0s-kube-scheduler
  konnectivity:
    agentPort: 8132
    adminPort: 8133
