apiVersion: k0s.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s
spec:
  api:
    address: 192.168.1.2
    port: 6443
    k0sApiPort: 9443
    sans:
    - 192.168.1.2
    extraArgs:
      feature-gates: ServiceLBNodePortControl=true,MixedProtocolLBService=true
  storage:
    type: etcd
    etcd:
      peerAddress: 192.168.1.2
  network:
    podCIDR: 10.244.0.0/16
    serviceCIDR: 10.96.0.0/12
    provider: kuberouter
    kubeProxy:
      disabled: false
      mode: iptables
  podSecurityPolicy:
    defaultPolicy: 00-k0s-privileged
  telemetry:
    enabled: true
  installConfig:
    users:
      etcdUser: k0s-etcd
      kineUser: k0s-kube-apiserver
      konnectivityUser: k0s-konnectivity-server
      kubeAPIserverUser: k0s-kube-apiserver
      kubeSchedulerUser: k0s-kube-scheduler
  images:
    konnectivity:
      image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
    metricsserver:
      image: gcr.io/k8s-staging-metrics-server/metrics-server
    kubeproxy:
      image: k8s.gcr.io/kube-proxy
    coredns:
      image: docker.io/coredns/coredns
    kuberouter:
      cni:
        image: docker.io/cloudnativelabs/kube-router
      cniInstaller:
        image: quay.io/k0sproject/cni-node
    default_pull_policy: IfNotPresent
  konnectivity:
    agentPort: 8132
    adminPort: 8133
