---
kind: Namespace
apiVersion: v1
metadata:
  name: ingress-nginx
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1h0s
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ingress-nginx
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  valuesFrom:
  - kind: ConfigMap
    name: ingress-nginx-helm-chart-value-overrides
    valuesKey: values.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-nginx-helm-chart-value-overrides
  namespace: ingress-nginx
data:
  values.yaml: |-
    controller:
      extraArgs:
        default-ssl-certificate: default/local-tls
      config:
        enable-real-ip: "true"
        proxy-buffer-size: "16k"
        proxy-body-size: "512M"
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
      watchIngressWithoutClass: true
