---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: 1.18.2
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
  values:
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard_threads = 1
    toolbox:
      enabled: true
    cephClusterSpec:
      mon:
        count: 1
      mgr:
        count: 1
      storage:
        useAllNodes: false
        useAllDevices: false
        nodes:
        - name: talos-lje-xo8
          devicePathFilter: '^/dev/disk/by-id/nvme-.*(4TB|512GB|512HBJQ|INTEL).*'
      placement:
        all:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: node-role.kubernetes.io/control-plane
                  operator: DoesNotExist
      resources:
        osd:
          requests:
            cpu: '500m'
            memory: '2Gi'
    cephBlockPools:
    - name: builtin-mgr
      spec:
        name: .mgr
        failureDomain: osd
        replicated:
          size: 3
          requireSafeReplicaSize: true
        parameters:
          compression_mode: none
        mirroring:
          enabled: false
      storageClass:
        enabled: false
    cephFileSystems: []
    cephObjectStores: []
