{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "workspace-common",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "workspace-common"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": {
               "vault.hashicorp.com/agent-init-first": "true",
               "vault.hashicorp.com/agent-inject": "true",
               "vault.hashicorp.com/agent-inject-secret-authorized_keys": "homeserver/data/ssh",
               "vault.hashicorp.com/agent-inject-secret-id_rsa": "homeserver/data/ssh",
               "vault.hashicorp.com/agent-inject-template-authorized_keys": "{{ with secret \"homeserver/data/ssh\" -}}\n{{ .Data.data.public_key }}\n{{- end }}\n",
               "vault.hashicorp.com/agent-inject-template-id_rsa": "{{ with secret \"homeserver/data/ssh\" -}}\n{{ .Data.data.private_key }}\n{{- end }}\n",
               "vault.hashicorp.com/agent-pre-populate-only": "true",
               "vault.hashicorp.com/role": "workspace_ssh"
            },
            "labels": {
               "app.kubernetes.io/name": "workspace-common"
            }
         },
         "spec": {
            "containers": [
               {
                  "command": [
                     "/bin/bash",
                     "-ex",
                     "-c",
                     "cp /vault/secrets/authorized_keys /root/.ssh/\ncp /vault/secrets/id_rsa /root/.ssh/\nmkdir /run/sshd\nchmod 700 /root/.ssh && chmod 600 /root/.ssh/*\n\nexec /usr/sbin/sshd -D -f /etc/config/sshd_config\n"
                  ],
                  "env": [
                     {
                        "name": "TZ",
                        "value": "Australia/Sydney"
                     }
                  ],
                  "image": "registry.local.d20.fan/fancl20/workspace",
                  "name": "workspace-common",
                  "volumeMounts": [
                     {
                        "mountPath": "/etc/config",
                        "name": "config"
                     },
                     {
                        "mountPath": "/root",
                        "name": "data",
                        "subPath": "workspaces/common"
                     },
                     {
                        "mountPath": "/root/.ssh",
                        "name": "ssh"
                     }
                  ]
               }
            ],
            "serviceAccountName": "workspace-common",
            "volumes": [
               {
                  "name": "data",
                  "persistentVolumeClaim": {
                     "claimName": "mass-storage"
                  }
               },
               {
                  "configMap": {
                     "name": "workspace-common"
                  },
                  "name": "config"
               },
               {
                  "emptyDir": { },
                  "name": "ssh"
               }
            ]
         }
      }
   }
}
