{
   "apiVersion": "kustomize.config.k8s.io/v1beta1",
   "configMapGenerator": [
      {
         "files": [
            "sshd_config"
         ],
         "name": "workspace-common",
         "namespace": "default"
      }
   ],
   "kind": "Kustomization",
   "resources": [
      "deployment.yaml",
      "service_workspace-common.yaml",
      "serviceaccount.yaml"
   ]
}
