{
   "apiVersion": "v1",
   "kind": "Service",
   "metadata": {
      "annotations": {
         "external-dns.alpha.kubernetes.io/hostname": "workspace-common.local.d20.fan"
      },
      "name": "workspace-common",
      "namespace": "default"
   },
   "spec": {
      "ports": [
         {
            "name": "ssh",
            "port": 22,
            "protocol": "TCP",
            "targetPort": 2222
         }
      ],
      "selector": {
         "app.kubernetes.io/name": "workspace-common"
      },
      "type": "ClusterIP"
   }
}
