---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clash-scripts
  namespace: continuous
data:
  fetch-latest.sh: |
    set -ex
    curl -s --fail -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/Dreamacro/clash/releases/tags/premium > metadata.json
    cat metadata.json | jq -rj '.assets[] | select(.name | startswith("clash-linux-amd64-20")) | .updated_at' | date -f - +%s | tr -d "\n" > "${RESULT_VERSION}"
    cat metadata.json | jq -rj '.assets[] | select(.name | startswith("clash-linux-amd64-20")) | .browser_download_url' > "${RESULT_URL}"
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: clash
  namespace: continuous
spec:
  params:
  - name: image
    value: clash
