apiVersion: batch/v1
kind: Job
metadata:
  name: images-build-push
  namespace: continuous
spec:
  template:
    spec:
      containers:
      - name: images-build-push
        image: curlimages/curl
        args: ["curl", "-X", "POST", "--data", "{}", "el-images-build-push.continuous.svc.cluster.local:8080"]
      restartPolicy: Never