---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 02-stage
  namespace: flux-system
spec:
  dependsOn:
  - name: 01-stage
  interval: 15m
  path: ./configs/clusters-ng/production/02-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
  # vault configs
  - apiVersion: v1
    kind: Secret
    name: vault-storage-key
    namespace: vault
  - apiVersion: v1
    kind: ConfigMap
    name: vault-helm-chart-value-overrides
    namespace: vault
  # ingress-nginx
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: ingress-nginx
    namespace: ingress-nginx
