---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 01-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 00-stage
  interval: 15m
  path: ./configs/clusters/production/01-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  components:
  - ../../components/terraform
  postBuild:
    substitute:
      layer_name: 01-stage
  healthChecks:
  # multus-cni
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: network-attachment-definitions.k8s.cni.cncf.io
  # metallb
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: ipaddresspools.metallb.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: l2advertisements.metallb.io
  # fluxcd
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: terraforms.infra.contrib.fluxcd.io
  # cert-manager
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: certificates.cert-manager.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: issuers.cert-manager.io
  # external-secrets
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: externalsecrets.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: secretstores.external-secrets.io
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: vaultdynamicsecrets.generators.external-secrets.io
  # ingress-nginx
  - apiVersion: helm.toolkit.fluxcd.io/v2beta1
    kind: HelmRelease
    name: ingress-nginx
    namespace: ingress-nginx
