---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 01-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 00-stage
  interval: 1m0s
  path: ./configs/clusters/production/01-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
