---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 01-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 00-stage
  interval: 1m0s
  path: ./configs/clusters/production/01-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
