---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 01-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 00-stage
  interval: 1m0s
  path: ./configs/clusters/production/01-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
    - apiVersion: apps/v1
      kind: DaemonSet
      name: kube-multus-ds
      namespace: kube-system
    - apiVersion: apps/v1
      kind: Deployment
      name: metallb-controller
      namespace: metallb-system
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-nginx-controller
      namespace: ingress-nginx
    - apiVersion: apps/v1
      kind: Deployment
      name: tf-controller
      namespace: flux-system
    # This is not part of the 00-stage but is required by 01-stage.
    # Manually apply the terraform in 01-stage for bootstrapping.
    - apiVersion: v1
      kind: Secret
      name: tf-controller-key
      namespace: flux-system
