---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: onepassword
  namespace: onepassword
spec:
  interval: 1h0s
  url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
  namespace: onepassword
spec:
  interval: 15m
  chart:
    spec:
      chart: connect
      sourceRef:
        kind: HelmRepository
        name: onepassword
