---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: multus-cni
  namespace: flux-system
spec:
  image: ghcr.io/k8snetworkplumbingwg/multus-cni
  interval: 1h
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: multus-cni
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: multus-cni
  policy:
    semver:
      range: 4.x
