---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 03-stage
  namespace: flux-system
spec:
  dependsOn:
    - name: 02-stage
  interval: 1m0s
  path: ./configs/clusters/production/03-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vault
      namespace: vault
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vaultauths.secrets.hashicorp.com
    - apiVersion: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      name: vaultstaticsecrets.secrets.hashicorp.com
