---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 03-stage
  namespace: flux-system
spec:
  dependsOn:
  - name: 02-stage
  interval: 15m
  path: ./configs/clusters/production/03-stage
  prune: true
  sourceRef:
    kind: GitRepository
    name: configs
  components:
    - ../../components/terraform
  postBuild:
    substitute:
      layer_name: 03-stage
  healthChecks:
  - apiVersion: apps/v1
    kind: StatefulSet
    name: vault
    namespace: vault
