{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImageRepository",
   "metadata": {
      "name": "calibre",
      "namespace": "flux-system"
   },
   "spec": {
      "image": "lscr.io/linuxserver/calibre-web",
      "interval": "1h"
   }
}
