{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "dae",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "extract": "$SEMVER-testing-$PATCH-$TESTING",
         "pattern": "^v(?P<SEMVER>[0-9.]+)+(?:\\.p)?(?P<PATCH>\\d+)?-testing-(?P<TESTING>.+)$"
      },
      "imageRepositoryRef": {
         "name": "dae"
      },
      "policy": {
         "semver": {
            "range": "*-testing-"
         }
      }
   }
}
