{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "debian",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "extract": "$timestamp",
         "pattern": "^testing-(?P<timestamp>\\d+)$"
      },
      "imageRepositoryRef": {
         "name": "debian"
      },
      "policy": {
         "alphabetical": {
            "order": "asc"
         }
      }
   }
}
