{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "openssh",
      "namespace": "flux-system"
   },
   "spec": {
      "filterTags": {
         "extract": "$SEMVER.$PATCH-ls$REVISION$LSVER",
         "pattern": "^(?P<SEMVER>[0-9.]+)_p(?P<PATCH>\\d+)-r(?P<REVISION>\\d+)-ls(?P<LSVER>\\d+)$"
      },
      "imageRepositoryRef": {
         "name": "openssh"
      },
      "policy": {
         "semver": {
            "range": "*-ls"
         }
      }
   }
}
