{
   "apiVersion": "image.toolkit.fluxcd.io/v1beta2",
   "kind": "ImagePolicy",
   "metadata": {
      "name": "workspace",
      "namespace": "flux-system"
   },
   "spec": {
      "imageRepositoryRef": {
         "name": "workspace"
      },
      "policy": {
         "alphabetical": {
            "order": "asc"
         }
      }
   }
}
