---
apiVersion: infra.contrib.fluxcd.io/v1alpha1
kind: Terraform
metadata:
  name: "placeholder"
  namespace: flux-system
spec:
  interval: 1h0s
  path: "placeholder"
  backendConfig:
    disable: true
  approvePlan: auto
  sourceRef:
    kind: GitRepository
    name: configs
  runnerPodTemplate:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-init-first: "true"
        vault.hashicorp.com/role: admin
        vault.hashicorp.com/agent-run-as-same-user: "true"
        vault.hashicorp.com/agent-inject-token: "true"
        vault.hashicorp.com/agent-inject-secret-gcp: gcp/roleset/admin/key
        vault.hashicorp.com/agent-inject-template-gcp: |
          {{ with secret "gcp/roleset/admin/key" -}}
          {{ .Data.private_key_data }}
          {{- end }}
    spec:
      env:
      - name: GOOGLE_APPLICATION_CREDENTIALS
        value: /home/runner/key.json
      - name: VAULT_ADDR
        value:  http://vault.vault.svc:8200/
      initContainers:
      - name: setup-creds
        image: ghcr.io/weaveworks/tf-runner:v0.14.0  # {"$imagepolicy": "flux-system:tf-runner"}
        command: ["/bin/sh", "-ec", "base64 -d /vault/secrets/gcp > /home/runner/key.json && cp /vault/secrets/token /home/runner/.vault-token"]
        securityContext:
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /home/runner
          name: home