{
   "apiVersion": "apps/v1",
   "kind": "Deployment",
   "metadata": {
      "name": "external-dns",
      "namespace": "default"
   },
   "spec": {
      "replicas": 1,
      "selector": {
         "matchLabels": {
            "app.kubernetes.io/name": "external-dns"
         }
      },
      "strategy": {
         "rollingUpdate": {
            "maxSurge": 0,
            "maxUnavailable": "100%"
         }
      },
      "template": {
         "metadata": {
            "annotations": { },
            "labels": {
               "app.kubernetes.io/name": "external-dns"
            }
         },
         "spec": {
            "containers": [
               {
                  "args": [
                     "--registry=txt",
                     "--txt-prefix=external-dns-",
                     "--txt-owner-id=k8s",
                     "--provider=rfc2136",
                     "--rfc2136-host=bind9.default",
                     "--rfc2136-port=53",
                     "--rfc2136-zone=local.d20.fan",
                     "--rfc2136-tsig-keyname=bind9-externaldns",
                     "--rfc2136-tsig-axfr",
                     "--source=service",
                     "--source=ingress",
                     "--domain-filter=local.d20.fan"
                  ],
                  "envFrom": [
                     {
                        "secretRef": {
                           "name": "external-dns"
                        }
                     }
                  ],
                  "image": "registry.k8s.io/external-dns/external-dns",
                  "name": "external-dns",
                  "resources": {
                     "limits": {
                        "cpu": "200m",
                        "memory": "64Mi"
                     },
                     "requests": {
                        "cpu": "100m",
                        "memory": "32Mi"
                     }
                  }
               }
            ],
            "securityContext": {
               "fsGroup": 1000,
               "fsGroupChangePolicy": "OnRootMismatch",
               "runAsGroup": 1000,
               "runAsUser": 1000
            },
            "serviceAccountName": "external-dns",
            "volumes": [ ]
         }
      }
   }
}
